name: cifar10-cnn-env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - absl-py=2.3.1=pyhd8ed1ab_0
  - backports.zstd=1.3.0=py311h71c1bcc_0
  - blas=1.0=mkl
  - brotli=1.2.0=h2d644bc_1
  - brotli-bin=1.2.0=hfd05255_1
  - brotli-python=1.2.0=py311hc5da9e4_1
  - bzip2=1.0.8=h0ad9c76_8
  - c-ares=1.34.6=hfd05255_0
  - ca-certificates=2025.11.12=h4c7d964_0
  - cairo=1.18.4=h477c42c_1
  - certifi=2025.11.12=pyhd8ed1ab_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - contourpy=1.3.3=py311h3fd045d_3
  - cuda-cccl=12.9.27=0
  - cuda-cccl_win-64=12.9.27=0
  - cuda-cudart=12.1.105=0
  - cuda-cudart-dev=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-libraries-dev=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvrtc-dev=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.9.19=0
  - cuda-opencl-dev=12.9.19=0
  - cuda-profiler-api=12.9.79=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.9=3
  - cycler=0.12.1=pyhcf101f3_2
  - double-conversion=3.4.0=hac47afa_0
  - filelock=3.20.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=py311h3f79411_0
  - freetype=2.14.1=h57928b3_0
  - fribidi=1.0.16=hfd05255_0
  - getopt-win32=0.1=h6a83c73_3
  - graphite2=1.3.14=hac47afa_2
  - grpcio=1.74.1=py311h989a076_1
  - gts=0.7.6=h6b5321d_4
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.3.0=h5a1b470_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=78.1=h637d24d_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - jinja2=3.1.6=pyhcf101f3_1
  - khronos-opencl-icd-loader=2024.10.24=h2466b09_1
  - kiwisolver=1.4.9=py311h275cad7_2
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libabseil=20250512.1=cxx17_habfad5f_0
  - libblas=3.9.0=12_win64_mkl
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libcblas=3.9.0=12_win64_mkl
  - libclang13=21.1.7=default_ha2db4b5_3
  - libcublas=12.1.0.26=0
  - libcublas-dev=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufft-dev=11.0.2.4=0
  - libcurand=10.3.10.19=0
  - libcurand-dev=10.3.10.19=0
  - libcusolver=11.4.4.55=0
  - libcusolver-dev=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libcusparse-dev=12.0.2.55=0
  - libdeflate=1.25=h51727cc_0
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h8ee18e1_16
  - libgd=2.3.3=h4974f7c_12
  - libglib=2.86.3=h0c9aed9_0
  - libgomp=15.2.0=h8ee18e1_16
  - libgrpc=1.74.1=h317e13b_1
  - libhwloc=2.12.1=default_h4379cf1_1003
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - liblapack=3.9.0=12_win64_mkl
  - liblzma=5.8.1=h2466b09_2
  - libnpp=12.0.2.50=0
  - libnpp-dev=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjitlink-dev=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libnvjpeg-dev=12.1.1.14=0
  - libpng=1.6.53=h7351971_0
  - libprotobuf=6.31.1=hdcda5b4_4
  - libre2-11=2025.11.05=h0eb2380_0
  - libsqlite=3.51.1=hf5d6505_1
  - libtiff=4.7.1=h8f73337_1
  - libuv=1.51.0=hfd05255_1
  - libvulkan-loader=1.4.328.1=h477610d_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.15.1=h779ef1b_1
  - libxml2-16=2.15.1=h3cfd58e_1
  - libxslt=1.1.43=h0fbe4c1_1
  - libzlib=1.3.1=h2466b09_2
  - markdown=3.10=pyhcf101f3_1
  - markupsafe=3.0.3=py311h3f79411_0
  - matplotlib=3.10.8=py311h1ea47a8_0
  - matplotlib-base=3.10.8=py311h1675fdf_0
  - ml_dtypes=0.5.4=np2py311hf2e69b3_0
  - mpmath=1.3.0=pyhd8ed1ab_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - networkx=3.6.1=pyhcf101f3_0
  - numpy=2.4.0=py311h80b3fa1_0
  - onnx=1.20.0=py311hee86750_1
  - onnx-ir=0.1.12=pyhd8ed1ab_0
  - onnxscript=0.5.6=pyhd8ed1ab_0
  - opencl-headers=2025.06.13=he0c23c2_0
  - openjpeg=2.5.4=h24db6dd_0
  - openssl=3.6.0=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - pango=1.56.4=h03d888a_0
  - pcre2=10.47=hd2b5f0e_0
  - pillow=12.0.0=py311h17b8079_2
  - pip=25.3=pyh8b19718_0
  - pixman=0.46.4=h5112557_1
  - protobuf=6.31.1=py311heca59f8_2
  - pthread-stubs=0.4=h0e40799_1002
  - pyparsing=3.3.1=pyhcf101f3_0
  - pyside6=6.10.1=py311hf70c7b4_0
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.11.14=h0159041_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.11=8_cp311
  - pytorch=2.3.1=py3.11_cuda12.1_cudnn8_0
  - pytorch-cuda=12.1=hde6ce7c_6
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.3=py311h3f79411_0
  - qhull=2020.2=hc790b64_5
  - qt6-main=6.10.1=h68b6638_4
  - re2=2025.11.05=ha104f34_0
  - requests=2.32.5=pyhcf101f3_1
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - sympy=1.14.0=pyh04b8f61_5
  - tensorboard=2.20.0=pyhe01879c_0
  - tensorboard-data-server=0.7.0=py311h1ea47a8_4
  - tk=8.6.13=h2c6b04d_3
  - tornado=6.5.4=py311h3485c13_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=hc9c84f9_1
  - ucrt=10.0.26100.0=h57928b3_0
  - unicodedata2=17.0.0=py311h3485c13_1
  - urllib3=2.6.2=pyhd8ed1ab_0
  - vc=14.3=h2b53caa_33
  - vc14_runtime=14.44.35208=h818238b_33
  - vcomp14=14.44.35208=h818238b_33
  - vs2015_runtime=14.44.35208=h38c0c73_33
  - werkzeug=3.1.4=pyhcf101f3_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - xorg-libice=1.1.2=h0e40799_0
  - xorg-libsm=1.2.6=h0e40799_0
  - xorg-libx11=1.8.12=hf48077a_0
  - xorg-libxau=1.0.12=hba3369d_1
  - xorg-libxdmcp=1.1.5=hba3369d_1
  - xorg-libxext=1.3.6=h0e40799_0
  - xorg-libxpm=3.5.17=h0e40799_1
  - xorg-libxt=1.3.1=h0e40799_0
  - yaml=0.2.5=h6a83c73_3
  - zipp=3.23.0=pyhcf101f3_1
  - zlib-ng=2.3.2=h0261ad2_1
  - zstd=1.5.7=h534d264_6
  - pip:
      - fsspec==2025.12.0
      - graphviz==0.21
      - intel-openmp==2021.4.0
      - mkl==2021.4.0
      - tbb==2021.13.1
      - torchinfo==1.8.0
      - torchvision==0.18.1
      - torchviz==0.0.3
prefix: D:\anaconda\envs\cifar10-cnn-env
